In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/corporate_income_statement.csv')

In [3]:
df.head()

,symbol,fiscalDateEnding,reportedCurrency,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,...,depreciation,depreciationAndAmortization,incomeBeforeTax,incomeTaxExpense,interestAndDebtExpense,netIncomeFromContinuingOperations,comprehensiveIncomeNetOfTax,ebit,ebitda,netIncome
0,NVDA,2025-10-31,USD,4.184900e+10,5.700600e+10,1.515700e+10,1.515700e+10,3.601000e+10,1.134000e+09,4.705000e+09,...,NaN,751000000.0,3.793600e+10,6.026000e+09,NaN,3.191000e+10,NaN,3.799700e+10,3.874800e+10,3.191000e+10
1,NVDA,2025-07-31,USD,3.385300e+10,4.674300e+10,1.289000e+10,1.289000e+10,2.844000e+10,1.122000e+09,4.291000e+09,...,NaN,669000000.0,3.120600e+10,4.784000e+09,NaN,2.642200e+10,NaN,3.126800e+10,3.193700e+10,2.642200e+10
2,NVDA,2025-04-30,USD,2.666800e+10,4.406200e+10,1.739400e+10,1.739400e+10,2.163800e+10,1.041000e+09,3.989000e+09,...,NaN,611000000.0,2.191000e+10,3.135000e+09,NaN,1.877500e+10,NaN,2.197300e+10,2.258400e+10,1.877500e+10
3,NVDA,2025-01-31,USD,2.872300e+10,3.933100e+10,1.060800e+10,1.060800e+10,2.403400e+10,9.750000e+08,3.714000e+09,...,NaN,543000000.0,2.521700e+10,3.126000e+09,NaN,2.209100e+10,NaN,2.527800e+10,2.582100e+10,2.209100e+10
4,NVDA,2024-10-31,USD,2.615600e+10,3.508200e+10,8.926000e+09,8.926000e+09,2.186900e+10,8.970000e+08,3.390000e+09,...,NaN,478000000.0,2.231600e+10,3.007000e+09,NaN,1.930900e+10,NaN,2.237700e+10,2.285500e+10,1.930900e+10

In [4]:
df.shape

(1750, 27)

In [5]:
df.isnull().sum()

symbol                                  0
fiscalDateEnding                        0
reportedCurrency                        2
grossProfit                             4
totalRevenue                            0
costOfRevenue                           1
costofGoodsAndServicesSold              1
operatingIncome                         4
sellingGeneralAndAdministrative        64
researchAndDevelopment                320
operatingExpenses                       4
investmentIncomeNet                  1750
netInterestIncome                    1152
interestIncome                       1198
interestExpense                        21
nonInterestIncome                    1750
otherNonOperatingIncome               947
depreciation                         1750
depreciationAndAmortization            28
incomeBeforeTax                         4
incomeTaxExpense                        1
interestAndDebtExpense               1750
netIncomeFromContinuingOperations     166
comprehensiveIncomeNetOfTax          1750
ebit                                    4
ebitda                                 17
netIncome                               4
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
# Find rows containing at least one empty/blank cell
df[df.astype(str).apply(lambda x: x.str.strip() == '').any(axis=1)]

Empty DataFrame
Columns: [symbol, fiscalDateEnding, reportedCurrency, grossProfit, totalRevenue, costOfRevenue, costofGoodsAndServicesSold, operatingIncome, sellingGeneralAndAdministrative, researchAndDevelopment, operatingExpenses, investmentIncomeNet, netInterestIncome, interestIncome, interestExpense, nonInterestIncome, otherNonOperatingIncome, depreciation, depreciationAndAmortization, incomeBeforeTax, incomeTaxExpense, interestAndDebtExpense, netIncomeFromContinuingOperations, comprehensiveIncomeNetOfTax, ebit, ebitda, netIncome]
Index: []

[0 rows x 27 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1750 entries, 0 to 1749
Data columns (total 27 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   symbol                             1750 non-null   object
 1   fiscalDateEnding                   1750 non-null   object
 2   reportedCurrency                   1748 non-null   object
 3   grossProfit                        1746 non-null   float64
 4   totalRevenue                       1750 non-null   float64
 5   costOfRevenue                      1749 non-null   float64
 6   costofGoodsAndServicesSold         1749 non-null   float64
 7   operatingIncome                    1746 non-null   float64
 8   sellingGeneralAndAdministrative    1686 non-null   float64
 9   researchAndDevelopment             1430 non-null   float64
 10  operatingExpenses                  1746 non-null   float64
 11  investmentIncomeNet                0 non-null      float64
 12  netInterestIncome                  598 non-null    float64
 13  interestIncome                     552 non-null    float64
 14  interestExpense                    1729 non-null   float64
 15  nonInterestIncome                  0 non-null      float64
 16  otherNonOperatingIncome            803 non-null    float64
 17  depreciation                       0 non-null      float64
 18  depreciationAndAmortization        1722 non-null   float64
 19  incomeBeforeTax                    1746 non-null   float64
 20  incomeTaxExpense                   1749 non-null   float64
 21  interestAndDebtExpense             0 non-null      float64
 22  netIncomeFromContinuingOperations  1584 non-null   float64
 23  comprehensiveIncomeNetOfTax        0 non-null      float64
 24  ebit                               1746 non-null   float64
 25  ebitda                             1733 non-null   float64
 26  netIncome                          1746 non-null   float64
dtypes: float64(24), object(3)
memory usage: 369.3+ KB

In [11]:
df['fiscalDateEnding'] = pd.to_datetime(df['fiscalDateEnding'])

In [12]:
df.dtypes

symbol                                       object
fiscalDateEnding                     datetime64[ns]
reportedCurrency                             object
grossProfit                                 float64
totalRevenue                                float64
costOfRevenue                               float64
costofGoodsAndServicesSold                  float64
operatingIncome                             float64
sellingGeneralAndAdministrative             float64
researchAndDevelopment                      float64
operatingExpenses                           float64
investmentIncomeNet                         float64
netInterestIncome                           float64
interestIncome                              float64
interestExpense                             float64
nonInterestIncome                           float64
otherNonOperatingIncome                     float64
depreciation                                float64
depreciationAndAmortization                 float64
incomeBeforeTax                             float64
incomeTaxExpense                            float64
interestAndDebtExpense                      float64
netIncomeFromContinuingOperations           float64
comprehensiveIncomeNetOfTax                 float64
ebit                                        float64
ebitda                                      float64
netIncome                                   float64
dtype: object

In [13]:
# Remove columns where every value is missing
df = df.dropna(axis=1, how='all')

# Check the updated dataset shape
print("Updated shape:", df.shape)

# Display remaining columns
df.columns

Updated shape: (1750, 22)

Index(['symbol', 'fiscalDateEnding', 'reportedCurrency', 'grossProfit',
       'totalRevenue', 'costOfRevenue', 'costofGoodsAndServicesSold',
       'operatingIncome', 'sellingGeneralAndAdministrative',
       'researchAndDevelopment', 'operatingExpenses', 'netInterestIncome',
       'interestIncome', 'interestExpense', 'otherNonOperatingIncome',
       'depreciationAndAmortization', 'incomeBeforeTax', 'incomeTaxExpense',
       'netIncomeFromContinuingOperations', 'ebit', 'ebitda', 'netIncome'],
      dtype='object')

In [14]:
# Check remaining missing values after removing completely empty columns
df.isnull().sum()

symbol                                  0
fiscalDateEnding                        0
reportedCurrency                        2
grossProfit                             4
totalRevenue                            0
costOfRevenue                           1
costofGoodsAndServicesSold              1
operatingIncome                         4
sellingGeneralAndAdministrative        64
researchAndDevelopment                320
operatingExpenses                       4
netInterestIncome                    1152
interestIncome                       1198
interestExpense                        21
otherNonOperatingIncome               947
depreciationAndAmortization            28
incomeBeforeTax                         4
incomeTaxExpense                        1
netIncomeFromContinuingOperations     166
ebit                                    4
ebitda                                 17
netIncome                               4
dtype: int64

In [15]:
# Check the number of companies in the dataset
print("Number of companies:", df['symbol'].nunique())

# Display all company symbols
print(df['symbol'].unique())

Number of companies: 23
['NVDA' 'MSFT' 'AAPL' 'GOOG' 'AMZN' 'META' 'AVGO' 'TSM' 'TSLA' 'BRK-B'
 'JPM' 'ORCL' 'WMT' 'LLY' 'V' 'MA' 'NFLX' 'XOM' 'JNJ' 'COST' 'HD' 'BABA'
 'PLTR']

In [16]:
# Check the number of financial periods available for each company
df['symbol'].value_counts()

symbol
NVDA     81
MSFT     81
AAPL     81
GOOG     81
AMZN     81
BRK-B    81
TSM      81
COST     81
HD       81
JPM      81
ORCL     81
LLY      81
WMT      81
NFLX     81
MA       81
XOM      81
JNJ      81
V        78
AVGO     75
TSLA     72
META     63
BABA     58
PLTR     27
Name: count, dtype: int64

In [17]:
# Display NVIDIA's financial reporting dates in chronological order
df[df['symbol'] == 'NVDA'][['symbol', 'fiscalDateEnding']].sort_values('fiscalDateEnding')

   symbol fiscalDateEnding
80   NVDA       2005-10-31
79   NVDA       2006-01-31
78   NVDA       2006-04-30
77   NVDA       2006-07-31
76   NVDA       2006-10-31
..    ...              ...
4    NVDA       2024-10-31
3    NVDA       2025-01-31
2    NVDA       2025-04-30
1    NVDA       2025-07-31
0    NVDA       2025-10-31

[81 rows x 2 columns]

In [18]:
# Check missing values by company
missing_by_company = df.groupby('symbol').apply(
    lambda x: x.isnull().sum()
)

# Display the missing-value counts for each company
missing_by_company

/tmp/ipykernel_1042/4243141876.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  missing_by_company = df.groupby('symbol').apply(

,symbol,fiscalDateEnding,reportedCurrency,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,...,interestIncome,interestExpense,otherNonOperatingIncome,depreciationAndAmortization,incomeBeforeTax,incomeTaxExpense,netIncomeFromContinuingOperations,ebit,ebitda,netIncome
symbol,,,,,,,,,,,,,,,,,,,,,
AAPL,0,0,0,0,0,0,0,0,0,0,...,62,6,24,0,0,0,0,0,0,0
AMZN,0,0,0,0,0,0,0,0,0,0,...,55,0,25,0,0,0,1,0,0,0
AVGO,0,0,0,4,0,0,0,4,0,0,...,75,0,57,6,4,1,7,4,6,4
BABA,0,0,0,0,0,0,0,0,0,0,...,34,0,51,7,0,0,0,0,7,0
BRK-B,0,0,0,0,0,0,0,0,0,73,...,54,0,60,11,0,0,35,0,0,0
COST,0,0,0,0,0,0,0,0,62,81,...,62,3,76,0,0,0,62,0,0,0
GOOG,0,0,0,0,0,0,0,0,0,0,...,54,2,50,0,0,0,41,0,0,0
HD,0,0,0,0,0,0,0,0,1,37,...,56,0,41,0,0,0,11,0,0,0
JNJ,0,0,0,0,0,0,0,0,0,0,...,54,0,26,0,0,0,1,0,0,0
JPM,0,0,0,0,0,0,0,0,0,25,...,54,0,78,0,0,0,0,0,0,0
LLY,0,0,0,0,0,0,0,0,0,0,...,54,0,47,0,0,0,0,0,0,0
MA,0,0,0,0,0,0,0,0,0,27,...,57,0,26,0,0,0,0,0,0,0
META,0,0,0,0,0,0,0,0,0,0,...,36,0,21,4,0,0,0,0,4,0
MSFT,0,0,0,0,0,0,0,0,0,0,...,57,0,27,0,0,0,0,0,0,0
NFLX,0,0,0,0,0,0,0,0,0,0,...,59,0,25,0,0,0,0,0,0,0
NVDA,0,0,0,0,0,0,0,0,0,0,...,54,0,28,0,0,0,0,0,0,0
ORCL,0,0,0,0,0,0,0,0,0,0,...,54,0,47,0,0,0,1,0,0,0
PLTR,0,0,2,0,0,0,0,0,0,0,...,2,9,17,0,0,0,2,0,0,0
TSLA,0,0,0,0,0,0,0,0,1,0,...,45,0,26,0,0,0,4,0,0,0
TSM,0,0,0,0,0,0,0,0,0,0,...,54,0,74,0,0,0,0,0,0,0
V,0,0,0,0,0,1,1,0,0,28,...,55,1,23,0,0,0,1,0,0,0
WMT,0,0,0,0,0,0,0,0,0,27,...,54,0,57,0,0,0,0,0,0,0
XOM,0,0,0,0,0,0,0,0,0,22,...,57,0,41,0,0,0,0,0,0,0

In [20]:
# Define the core financial columns used for the dashboard
core_columns = [
    'grossProfit',
    'operatingIncome',
    'operatingExpenses',
    'netIncome'
]

# Display rows containing missing values in the core financial columns
df[df[core_columns].isnull().any(axis=1)][
    ['symbol', 'fiscalDateEnding'] + core_columns
]

,symbol,fiscalDateEnding,grossProfit,operatingIncome,operatingExpenses,netIncome
539,AVGO,2007-10-31,NaN,NaN,NaN,NaN
540,AVGO,2007-07-31,NaN,NaN,NaN,NaN
541,AVGO,2007-04-30,NaN,NaN,NaN,NaN
542,AVGO,2007-01-31,NaN,NaN,NaN,NaN

In [21]:
# Remove rows with missing values in the core financial columns
df = df.dropna(subset=core_columns)

# Reset the row index after removing the incomplete records
df = df.reset_index(drop=True)

# Check the updated dataset shape
print("Updated shape:", df.shape)

Updated shape: (1746, 22)

In [22]:
# Select the variables needed for the financial analysis dashboard
financial_df = df[[
    'symbol',
    'fiscalDateEnding',
    'reportedCurrency',
    'totalRevenue',
    'costOfRevenue',
    'grossProfit',
    'operatingExpenses',
    'operatingIncome',
    'researchAndDevelopment',
    'sellingGeneralAndAdministrative',
    'netIncome'
]].copy()

# Preview the selected financial data
financial_df.head()

,symbol,fiscalDateEnding,reportedCurrency,totalRevenue,costOfRevenue,grossProfit,operatingExpenses,operatingIncome,researchAndDevelopment,sellingGeneralAndAdministrative,netIncome
0,NVDA,2025-10-31,USD,5.700600e+10,1.515700e+10,4.184900e+10,5.839000e+09,3.601000e+10,4.705000e+09,1.134000e+09,3.191000e+10
1,NVDA,2025-07-31,USD,4.674300e+10,1.289000e+10,3.385300e+10,5.413000e+09,2.844000e+10,4.291000e+09,1.122000e+09,2.642200e+10
2,NVDA,2025-04-30,USD,4.406200e+10,1.739400e+10,2.666800e+10,5.030000e+09,2.163800e+10,3.989000e+09,1.041000e+09,1.877500e+10
3,NVDA,2025-01-31,USD,3.933100e+10,1.060800e+10,2.872300e+10,4.689000e+09,2.403400e+10,3.714000e+09,9.750000e+08,2.209100e+10
4,NVDA,2024-10-31,USD,3.508200e+10,8.926000e+09,2.615600e+10,4.287000e+09,2.186900e+10,3.390000e+09,8.970000e+08,1.930900e+10

In [23]:
# Calculate gross profit margin as a percentage of total revenue
financial_df['grossMarginPct'] = (
    financial_df['grossProfit'] / financial_df['totalRevenue']
) * 100

# Preview the new gross margin variable
financial_df[
    ['symbol', 'fiscalDateEnding', 'totalRevenue',
     'grossProfit', 'grossMarginPct']
].head()

  symbol fiscalDateEnding  totalRevenue   grossProfit  grossMarginPct
0   NVDA       2025-10-31  5.700600e+10  4.184900e+10       73.411571
1   NVDA       2025-07-31  4.674300e+10  3.385300e+10       72.423678
2   NVDA       2025-04-30  4.406200e+10  2.666800e+10       60.523807
3   NVDA       2025-01-31  3.933100e+10  2.872300e+10       73.028908
4   NVDA       2024-10-31  3.508200e+10  2.615600e+10       74.556753

In [33]:
# Sort each company's financial records from oldest to newest
financial_df = financial_df.sort_values(
    ['symbol', 'fiscalDateEnding']
).reset_index(drop=True)

# Preview NVIDIA dates to verify chronological order
financial_df[
    financial_df['symbol'] == 'NVDA'
][['symbol', 'fiscalDateEnding', 'totalRevenue']].head(10)

     symbol fiscalDateEnding  totalRevenue
1164   NVDA       2005-10-31  5.834150e+08
1165   NVDA       2006-01-31  6.336140e+08
1166   NVDA       2006-04-30  6.818070e+08
1167   NVDA       2006-07-31  6.875000e+08
1168   NVDA       2006-10-31  8.205720e+08
1169   NVDA       2007-01-31  8.788730e+08
1170   NVDA       2007-04-30  8.442800e+08
1171   NVDA       2007-07-31  9.352530e+08
1172   NVDA       2007-10-31  1.115597e+09
1173   NVDA       2008-01-31  1.202730e+09

In [37]:
# Calculate gross margin percentage
financial_df['grossMarginPct'] = (
    financial_df['grossProfit'] / financial_df['totalRevenue']
) * 100

# Calculate operating margin percentage
financial_df['operatingMarginPct'] = (
    financial_df['operatingIncome'] / financial_df['totalRevenue']
) * 100

# Calculate net profit margin percentage
financial_df['netProfitMarginPct'] = (
    financial_df['netIncome'] / financial_df['totalRevenue']
) * 100

# Calculate operating expense ratio as a percentage of revenue
financial_df['operatingExpenseRatioPct'] = (
    financial_df['operatingExpenses'] / financial_df['totalRevenue']
) * 100

In [38]:
# Calculate quarter-over-quarter revenue growth percentage
financial_df['revenueGrowthQoQPct'] = (
    financial_df.groupby('symbol')['totalRevenue']
    .pct_change() * 100
)

# Calculate year-over-year revenue growth percentage
financial_df['revenueGrowthYoYPct'] = (
    financial_df.groupby('symbol')['totalRevenue']
    .pct_change(periods=4) * 100
)

# Calculate quarter-over-quarter operating expense growth percentage
financial_df['operatingExpenseGrowthQoQPct'] = (
    financial_df.groupby('symbol')['operatingExpenses']
    .pct_change() * 100
)

# Calculate quarter-over-quarter net income growth percentage
financial_df['netIncomeGrowthQoQPct'] = (
    financial_df.groupby('symbol')['netIncome']
    .pct_change() * 100
)

In [39]:
# Preview the dataset with all constructed financial metrics
financial_df.head(10)

,symbol,fiscalDateEnding,reportedCurrency,totalRevenue,costOfRevenue,grossProfit,operatingExpenses,operatingIncome,researchAndDevelopment,sellingGeneralAndAdministrative,netIncome,grossMarginPct,revenueGrowthQoQPct,revenueGrowthYoYPct,operatingExpenseGrowthQoQPct,netIncomeGrowthQoQPct,operatingMarginPct,netProfitMarginPct,operatingExpenseRatioPct
0,AAPL,2005-09-30,USD,3.678000e+09,2.643000e+09,1.035000e+09,6.170000e+08,4.180000e+08,147000000.0,470000000.0,4.300000e+08,28.140294,NaN,NaN,NaN,NaN,11.364872,11.691136,16.775421
1,AAPL,2005-12-31,USD,5.749000e+09,4.185000e+09,1.564000e+09,8.140000e+08,7.500000e+08,182000000.0,632000000.0,5.650000e+08,27.204731,56.307776,NaN,31.928687,31.395349,13.045747,9.827796,14.158984
2,AAPL,2006-03-31,USD,4.359000e+09,3.062000e+09,1.297000e+09,7.680000e+08,5.290000e+08,176000000.0,592000000.0,4.100000e+08,29.754531,-24.178118,NaN,-5.651106,-27.433628,12.135811,9.405827,17.618720
3,AAPL,2006-06-30,USD,4.370000e+09,3.045000e+09,1.325000e+09,7.590000e+08,5.660000e+08,175000000.0,584000000.0,4.720000e+08,30.320366,0.252351,NaN,-1.171875,15.121951,12.951945,10.800915,17.368421
4,AAPL,2006-09-30,USD,4.370000e+09,3.425000e+09,1.412000e+09,8.040000e+08,6.080000e+08,179000000.0,584000000.0,5.420000e+08,32.311213,0.000000,18.814573,5.928854,14.830508,13.913043,12.402746,18.398169
5,AAPL,2006-12-31,USD,7.115000e+09,4.895000e+09,2.220000e+09,8.980000e+08,1.322000e+09,184000000.0,714000000.0,1.004000e+09,31.201687,62.814645,23.760654,11.691542,85.239852,18.580464,14.111033,12.621223
6,AAPL,2007-03-31,USD,5.264000e+09,3.415000e+09,1.849000e+09,8.630000e+08,9.860000e+08,183000000.0,680000000.0,7.700000e+08,35.125380,-26.015460,20.761643,-3.897550,-23.306773,18.731003,14.627660,16.394377
7,AAPL,2007-06-30,USD,5.410000e+09,3.415000e+09,1.995000e+09,9.540000e+08,1.041000e+09,208000000.0,746000000.0,8.180000e+08,36.876155,2.773556,23.798627,10.544612,6.233766,19.242144,15.120148,17.634011
8,AAPL,2007-09-30,USD,6.217000e+09,4.127000e+09,2.090000e+09,1.030000e+09,1.060000e+09,207000000.0,823000000.0,9.040000e+08,33.617500,14.916821,42.265446,7.966457,10.513447,17.050024,14.540775,16.567476
9,AAPL,2007-12-31,USD,9.608000e+09,6.276000e+09,3.332000e+09,1.206000e+09,2.126000e+09,246000000.0,960000000.0,1.581000e+09,34.679434,54.543992,35.038651,17.087379,74.889381,22.127394,16.455037,12.552040

In [40]:
# Export the cleaned financial dataset with constructed metrics for Tableau
financial_df.to_csv(
    'financial_analysis_tableau.csv',
    index=False
)

# Download the final CSV file
from google.colab import files

files.download('financial_analysis_tableau.csv')