In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/product_sales_dataset_final.csv')

In [3]:
df.head()

,Order_ID,Order_Date,Customer_Name,City,State,Region,Country,Category,Sub_Category,Product_Name,Quantity,Unit_Price,Revenue,Profit
0,1,08-23-23,Bianca Brown,Jackson,Mississippi,South,United States,Accessories,Small Electronics,Phone Case,3,201.01,603.03,221.49
1,2,12-20-24,Jared Edwards,Grand Rapids,Michigan,Centre,United States,Accessories,Small Electronics,Charging Cable,4,74.30,297.20,97.09
2,3,01-29-24,Susan Valdez,Minneapolis,Minnesota,Centre,United States,Clothing & Apparel,Sportswear,Nike Air Force 1,1,68.19,68.19,25.47
3,4,11-29-24,Tina Williams,Tallahassee,Florida,South,United States,Clothing & Apparel,Sportswear,Adidas Tracksuit,3,209.64,628.92,231.38
4,5,09-21-23,Catherine Gordon,Baltimore,Maryland,East,United States,Accessories,Bags,Backpack,1,216.63,216.63,42.46

In [4]:
df.shape

(200000, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Order_ID       200000 non-null  int64
 1   Order_Date     200000 non-null  object
 2   Customer_Name  200000 non-null  object
 3   City           200000 non-null  object
 4   State          200000 non-null  object
 5   Region         200000 non-null  object
 6   Country        200000 non-null  object
 7   Category       200000 non-null  object
 8   Sub_Category   200000 non-null  object
 9   Product_Name   200000 non-null  object
 10  Quantity       200000 non-null  int64
 11   Unit_Price    200000 non-null  float64
 12   Revenue       200000 non-null  float64
 13   Profit        200000 non-null  float64
dtypes: float64(3), int64(2), object(9)
memory usage: 21.4+ MB

In [6]:
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_Name    0
City             0
State            0
Region           0
Country          0
Category         0
Sub_Category     0
Product_Name     0
Quantity         0
 Unit_Price      0
 Revenue         0
 Profit          0
dtype: int64

In [7]:
df[df.astype(str).apply(lambda x: x.str.strip() == '').any(axis =1)]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_Name, City, State, Region, Country, Category, Sub_Category, Product_Name, Quantity,  Unit_Price ,  Revenue ,  Profit ]
Index: []

In [8]:
df.duplicated().sum()

np.int64(0)

In [11]:
#convert Order_date from text to datetime
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [14]:
df.dtypes

Order_ID                  int64
Order_Date       datetime64[ns]
Customer_Name            object
City                     object
State                    object
Region                   object
Country                  object
Category                 object
Sub_Category             object
Product_Name             object
Quantity                  int64
 Unit_Price             float64
 Revenue                float64
 Profit                 float64
dtype: object

In [15]:
df.describe()

,Order_ID,Order_Date,Quantity,Unit_Price,Revenue,Profit
count,200000.000000,200000,200000.000000,200000.000000,200000.000000,200000.000000
mean,100000.500000,2024-02-11 17:22:01.632000,1.854000,382.855615,712.038725,157.743041
min,1.000000,2023-01-01 00:00:00,1.000000,17.030000,17.030000,3.920000
25%,50000.750000,2023-09-12 00:00:00,1.000000,162.760000,229.187500,59.210000
50%,100000.500000,2024-01-02 00:00:00,1.000000,303.545000,464.880000,109.530000
75%,150000.250000,2024-09-13 00:00:00,2.000000,562.252500,881.302500,199.402500
max,200000.000000,2024-12-31 00:00:00,11.000000,1432.000000,9014.250000,2763.720000
std,57735.171256,NaN,1.100536,276.870235,742.471556,155.689581

In [16]:
#Check the number of unique products, categories, and sub-categories
print("Products:", df['Product_Name'].nunique())
print("Categories:", df['Category'].nunique())
print("Sub-Categories:", df['Sub_Category'].nunique())

Products: 49
Categories: 4
Sub-Categories: 19

In [17]:
#Display the unique categories, sub-categories, and products
print("Categories:")
print(df['Category'].unique())

print("\nSub-Categories:")
print(df['Sub_Category'].unique())

print("\nProducts:")
print(df['Product_Name'].unique())

Categories:
['Accessories' 'Clothing & Apparel' 'Electronics' 'Home & Furniture']

Sub-Categories:
['Small Electronics' 'Sportswear' 'Bags' 'Home Appliances' 'Wearables'
 "Men's Wear" 'Footwear' 'Smartphones' "Women's Wear"
 'Wearable Accessories' 'Tablets' 'Kids Wear' 'Storage' 'Bedding'
 'TVs & Audio' 'Home Decor' 'Laptops' 'Kitchenware' 'Furniture']

Products:
['Phone Case' 'Charging Cable' 'Nike Air Force 1' 'Adidas Tracksuit'
 'Backpack' 'Instant Pot' 'Apple Watch' "Levi's Jeans" 'Timberland Boots'
 'Apple iPhone 14' 'Old Navy Dress' 'Watch Strap' 'Samsung Galaxy Tab'
 "Carter's Onesie" 'Storage Rack' 'GAP Hoodie' 'KitchenAid Mixer' 'Wallet'
 'Power Bank' 'Samsung Galaxy S23' 'Tote Bag' 'Tempur-Pedic Mattress'
 'LG OLED TV' 'Google Pixel 7' 'Throw Pillows' 'MacBook Air'
 'Nike Running Shoes' 'Brooklinen Sheets' "Children's Hoodie" 'Belt'
 'Under Armour T-Shirt' 'iPad Pro' 'Ashley Recliner' 'Zara Blouse'
 'IKEA Sofa' 'Vase' 'Wall Art' 'Closet Organizer' 'Lenovo ThinkPad'
 'Fitbit Charge' 'Bose Soundbar' 'Crocs' 'Dell XPS 13' 'Sunglasses'
 'Sony Bravia TV' 'Office Chair' 'Cookware Set' 'Dining Table Set'
 'Dyson Vacuum']

In [18]:
#Export the cleaned dataset to CSV and download the file
df.to_csv('product_performance_cleaned.csv', index=False)

from google.colab import files
files.download('product_performance_cleaned.csv')